/*
 * Team 4909, Bionics
 * Billerica Memorial High School
 *
 * Copyright:
 *   2021 Bionics
 *
 * License:
 *   MIT: https://opensource.org/licenses/MIT
 *   See the LICENSE file in the project's top-level directory for details.
 */

package frc.robot;


import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.TimedRobot;
import edu.wpi.first.wpilibj.shuffleboard.EventImportance;
import edu.wpi.first.wpilibj.shuffleboard.Shuffleboard;
import edu.wpi.first.wpilibj2.command.CommandScheduler;
import edu.wpi.first.wpilibj2.command.button.JoystickButton;
import frc.bionic.TrajectoryUtils;
import frc.bionic.UserInterfaceElement;
import frc.bionic.swerve.command.DriveWithJoystick;
import frc.peyton.Drivetrain;

public class Robot extends TimedRobot {
  private final Joystick m_controller = new Joystick(0);
  private final Drivetrain m_swerve = new Drivetrain();



  @Override
  public void robotInit() {

    UserInterface.registerObject("Drivetrain", new UserInterfaceElement<Drivetrain>(m_swerve));
    // Set the scheduler to log Shuffleboard events for command initialize, interrupt, finish
    CommandScheduler.getInstance().onCommandInitialize(command -> Shuffleboard.addEventMarker(
        "Command initialized", command.getName(), EventImportance.kNormal));
    CommandScheduler.getInstance().onCommandInterrupt(command -> Shuffleboard.addEventMarker(
        "Command interrupted", command.getName(), EventImportance.kNormal));
    CommandScheduler.getInstance().onCommandFinish(command -> Shuffleboard.addEventMarker(
        "Command finished", command.getName(), EventImportance.kNormal));

    m_swerve.setDefaultCommand(new DriveWithJoystick(m_swerve, m_controller));

    new JoystickButton(m_controller, 11).whileHeld(() -> m_swerve.lockInPlace(), m_swerve);
  }

  @Override
  public void robotPeriodic() {
    m_swerve.periodic();
  }

  @Override
  public void teleopInit() {
  }

  @Override
  public void teleopPeriodic() {
    // driveWithJoystick();
    CommandScheduler.getInstance().run();
  }

  @Override
  public void autonomousInit(){
    //Runs the Command Scheduler
    CommandScheduler.getInstance().run();
    //Starts the process of generating a trajectory
    UserInterface.runTrajectory();
    //Schedules the actual command generated by the swerve controller command
    // new TrajectoryUtils().getSwerveControllerCommand().schedule();
  }

  
}
